import { SelectItem } from "@/components/ui/select"

export const CountryList = () => (
  <>
  <SelectItem value="12">Afghanistan</SelectItem>
  <SelectItem value="13">Aland Islands</SelectItem>
  <SelectItem value="14">Albania</SelectItem>
  <SelectItem value="15">Algeria</SelectItem>
  <SelectItem value="16">American Samoa</SelectItem>
  <SelectItem value="17">Andorra</SelectItem>
  <SelectItem value="18">Angola</SelectItem>
  <SelectItem value="19">Anguilla</SelectItem>
  <SelectItem value="20">Antarctica</SelectItem>
  <SelectItem value="21">Antigua and Barbuda</SelectItem>
  <SelectItem value="22">Argentina</SelectItem>
  <SelectItem value="23">Armenia</SelectItem>
  <SelectItem value="24">Aruba</SelectItem>
  <SelectItem value="25">Ascension Island</SelectItem>
  <SelectItem value="5">Australia</SelectItem>
  <SelectItem value="26">Austria</SelectItem>
  <SelectItem value="27">Azerbaijan</SelectItem>
  <SelectItem value="28">Bahamas</SelectItem>
  <SelectItem value="29">Bahrain</SelectItem>
  <SelectItem value="30">Bangladesh</SelectItem>
  <SelectItem value="31">Barbados</SelectItem>
  <SelectItem value="32">Belarus</SelectItem>
  <SelectItem value="9">Belgium</SelectItem>
  <SelectItem value="33">Belize</SelectItem>
  <SelectItem value="34">Benin</SelectItem>
  <SelectItem value="35">Bermuda</SelectItem>
  <SelectItem value="36">Bhutan</SelectItem>
  <SelectItem value="37">Bolivia, Plurinational State of</SelectItem>
  <SelectItem value="38">Bonaire, Sint Eustatius and Saba</SelectItem>
  <SelectItem value="39">Bosnia and Herzegovina</SelectItem>
  <SelectItem value="40">Botswana</SelectItem>
  <SelectItem value="41">Bouvet Island</SelectItem>
  <SelectItem value="42">Brazil</SelectItem>
  <SelectItem value="43">British Indian Ocean Territory</SelectItem>
  <SelectItem value="44">Brunei Darussalam</SelectItem>
  <SelectItem value="45">Bulgaria</SelectItem>
  <SelectItem value="46">Burkina Faso</SelectItem>
  <SelectItem value="47">Burundi</SelectItem>
  <SelectItem value="48">Cambodia</SelectItem>
  <SelectItem value="49">Cameroon</SelectItem>
  <SelectItem value="4">Canada</SelectItem>
  <SelectItem value="50">Cape Verde</SelectItem>
  <SelectItem value="51">Cayman Islands</SelectItem>
  <SelectItem value="52">Central African Republic</SelectItem>
  <SelectItem value="53">Chad</SelectItem>
  <SelectItem value="54">Chile</SelectItem>
  <SelectItem value="55">China</SelectItem>
  <SelectItem value="56">Christmas Island</SelectItem>
  <SelectItem value="57">Cocos (Keeling) Islands</SelectItem>
  <SelectItem value="58">Colombia</SelectItem>
  <SelectItem value="59">Comoros</SelectItem>
  <SelectItem value="60">Congo</SelectItem>
  <SelectItem value="61">Congo, the Democratic Republic of the</SelectItem>
  <SelectItem value="62">Cook Islands</SelectItem>
  <SelectItem value="63">Costa Rica</SelectItem>
  <SelectItem value="64">Côte d'Ivoire</SelectItem>
  <SelectItem value="65">Croatia</SelectItem>
  <SelectItem value="66">Cuba</SelectItem>
  <SelectItem value="67">Curaçao</SelectItem>
  <SelectItem value="68">Cyprus</SelectItem>
  <SelectItem value="69">Czech Republic</SelectItem>
  <SelectItem value="70">Denmark</SelectItem>
  <SelectItem value="71">Djibouti</SelectItem>
  <SelectItem value="72">Dominica</SelectItem>
  <SelectItem value="73">Dominican Republic</SelectItem>
  <SelectItem value="74">Ecuador</SelectItem>
  <SelectItem value="75">Egypt</SelectItem>
  <SelectItem value="76">El Salvador</SelectItem>
  <SelectItem value="77">Equatorial Guinea</SelectItem>
  <SelectItem value="78">Eritrea</SelectItem>
  <SelectItem value="79">Estonia</SelectItem>
  <SelectItem value="80">Ethiopia</SelectItem>
  <SelectItem value="256">EU</SelectItem>
  <SelectItem value="81">Falkland Islands (Malvinas)</SelectItem>
  <SelectItem value="82">Faroe Islands</SelectItem>
  <SelectItem value="83">Fiji</SelectItem>
  <SelectItem value="84">Finland</SelectItem>
  <SelectItem value="85">France</SelectItem>
  <SelectItem value="86">French Guiana</SelectItem>
  <SelectItem value="87">French Polynesia</SelectItem>
  <SelectItem value="88">French Southern Territories</SelectItem>
  <SelectItem value="89">Gabon</SelectItem>
  <SelectItem value="90">Gambia</SelectItem>
  <SelectItem value="91">Georgia</SelectItem>
  <SelectItem value="10">Germany</SelectItem>
  <SelectItem value="92">Ghana</SelectItem>
  <SelectItem value="93">Gibraltar</SelectItem>
  <SelectItem value="94">Greece</SelectItem>
  <SelectItem value="95">Greenland</SelectItem>
  <SelectItem value="96">Grenada</SelectItem>
  <SelectItem value="97">Guadeloupe</SelectItem>
  <SelectItem value="98">Guam</SelectItem>
  <SelectItem value="99">Guatemala</SelectItem>
  <SelectItem value="100">Guernsey</SelectItem>
  <SelectItem value="101">Guinea</SelectItem>
  <SelectItem value="102">Guinea-Bissau</SelectItem>
  <SelectItem value="103">Guyana</SelectItem>
  <SelectItem value="104">Haiti</SelectItem>
  <SelectItem value="105">Heard Island and McDonald Islands</SelectItem>
  <SelectItem value="106">Holy See (Vatican City State)</SelectItem>
  <SelectItem value="107">Honduras</SelectItem>
  <SelectItem value="108">Hong Kong</SelectItem>
  <SelectItem value="109">Hungary</SelectItem>
  <SelectItem value="110">Iceland</SelectItem>
  <SelectItem value="111">India</SelectItem>
  <SelectItem value="112">Indonesia</SelectItem>
  <SelectItem value="113">Iran, Islamic Republic of</SelectItem>
  <SelectItem value="114">Iraq</SelectItem>
  <SelectItem value="2">Ireland</SelectItem>
  <SelectItem value="115">Isle of Man</SelectItem>
  <SelectItem value="116">Israel</SelectItem>
  <SelectItem value="117">Italy</SelectItem>
  <SelectItem value="118">Jamaica</SelectItem>
  <SelectItem value="119">Japan</SelectItem>
  <SelectItem value="120">Jersey</SelectItem>
  <SelectItem value="121">Jordan</SelectItem>
  <SelectItem value="122">Kazakhstan</SelectItem>
  <SelectItem value="123">Kenya</SelectItem>
  <SelectItem value="124">Kiribati</SelectItem>
  <SelectItem value="125">Korea, Democratic People's Republic of</SelectItem>
  <SelectItem value="126">Korea, Republic of</SelectItem>
  <SelectItem value="127">Kosovo</SelectItem>
  <SelectItem value="128">Kuwait</SelectItem>
  <SelectItem value="129">Kyrgyzstan</SelectItem>
  <SelectItem value="130">Lao People's Democratic Republic</SelectItem>
  <SelectItem value="131">Latvia</SelectItem>
  <SelectItem value="132">Lebanon</SelectItem>
  <SelectItem value="133">Lesotho</SelectItem>
  <SelectItem value="134">Liberia</SelectItem>
  <SelectItem value="135">Libya</SelectItem>
  <SelectItem value="136">Liechtenstein</SelectItem>
  <SelectItem value="137">Lithuania</SelectItem>
  <SelectItem value="138">Luxembourg</SelectItem>
  <SelectItem value="139">Macao</SelectItem>
  <SelectItem value="140">Macedonia, The Former Yugoslav Republic Of</SelectItem>
  <SelectItem value="141">Madagascar</SelectItem>
  <SelectItem value="142">Malawi</SelectItem>
  <SelectItem value="143">Malaysia</SelectItem>
  <SelectItem value="144">Maldives</SelectItem>
  <SelectItem value="145">Mali</SelectItem>
  <SelectItem value="146">Malta</SelectItem>
  <SelectItem value="147">Marshall Islands</SelectItem>
  <SelectItem value="148">Martinique</SelectItem>
  <SelectItem value="149">Mauritania</SelectItem>
  <SelectItem value="150">Mauritius</SelectItem>
  <SelectItem value="151">Mayotte</SelectItem>
  <SelectItem value="152">Mexico</SelectItem>
  <SelectItem value="153">Micronesia, Federated States of</SelectItem>
  <SelectItem value="154">Moldova, Republic of</SelectItem>
  <SelectItem value="155">Monaco</SelectItem>
  <SelectItem value="156">Mongolia</SelectItem>
  <SelectItem value="157">Montenegro</SelectItem>
  <SelectItem value="158">Montserrat</SelectItem>
  <SelectItem value="159">Morocco</SelectItem>
  <SelectItem value="160">Mozambique</SelectItem>
  <SelectItem value="161">Myanmar</SelectItem>
  <SelectItem value="162">Namibia</SelectItem>
  <SelectItem value="163">Nauru</SelectItem>
  <SelectItem value="164">Nepal</SelectItem>
  <SelectItem value="8">Netherlands</SelectItem>
  <SelectItem value="165">Netherlands Antilles</SelectItem>
  <SelectItem value="166">New Caledonia</SelectItem>
  <SelectItem value="167">New Zealand</SelectItem>
  <SelectItem value="168">Nicaragua</SelectItem>
  <SelectItem value="169">Niger</SelectItem>
  <SelectItem value="170">Nigeria</SelectItem>
  <SelectItem value="171">Niue</SelectItem>
  <SelectItem value="172">Norfolk Island</SelectItem>
  <SelectItem value="173">Northern Mariana Islands</SelectItem>
  <SelectItem value="174">Norway</SelectItem>
  <SelectItem value="175">Oman</SelectItem>
  <SelectItem value="176">Pakistan</SelectItem>
  <SelectItem value="177">Palau</SelectItem>
  <SelectItem value="178">Palestinian Territory, Occupied</SelectItem>
  <SelectItem value="179">Panama</SelectItem>
  <SelectItem value="180">Papua New Guinea</SelectItem>
  <SelectItem value="181">Paraguay</SelectItem>
  <SelectItem value="182">Peru</SelectItem>
  <SelectItem value="183">Philippines</SelectItem>
  <SelectItem value="184">Pitcairn</SelectItem>
  <SelectItem value="185">Poland</SelectItem>
  <SelectItem value="186">Portugal</SelectItem>
  <SelectItem value="187">Puerto Rico</SelectItem>
  <SelectItem value="188">Qatar</SelectItem>
  <SelectItem value="189">Reunion</SelectItem>
  <SelectItem value="190">Romania</SelectItem>
  <SelectItem value="191">Russian Federation</SelectItem>
  <SelectItem value="192">Rwanda</SelectItem>
  <SelectItem value="193">Saint Barthelemy</SelectItem>
  <SelectItem value="194">Saint Helena, Ascension and Tristan da Cunha</SelectItem>
  <SelectItem value="195">Saint Kitts and Nevis</SelectItem>
  <SelectItem value="196">Saint Lucia</SelectItem>
  <SelectItem value="197">Saint Martin (French part)</SelectItem>
  <SelectItem value="198">Saint Pierre and Miquelon</SelectItem>
  <SelectItem value="199">Saint Vincent and the Grenadines</SelectItem>
  <SelectItem value="200">Samoa</SelectItem>
  <SelectItem value="201">San Marino</SelectItem>
  <SelectItem value="202">Sao Tome and Principe</SelectItem>
  <SelectItem value="203">Saudi Arabia</SelectItem>
  <SelectItem value="204">Senegal</SelectItem>
  <SelectItem value="205">Serbia</SelectItem>
  <SelectItem value="206">Seychelles</SelectItem>
  <SelectItem value="207">Sierra Leone</SelectItem>
  <SelectItem value="208">Singapore</SelectItem>
  <SelectItem value="209">Sint Maarten (Dutch part)</SelectItem>
  <SelectItem value="210">Slovakia</SelectItem>
  <SelectItem value="211">Slovenia</SelectItem>
  <SelectItem value="212">Solomon Islands</SelectItem>
  <SelectItem value="213">Somalia</SelectItem>
  <SelectItem value="214">South Africa</SelectItem>
  <SelectItem value="215">South Georgia and the South Sandwich Islands</SelectItem>
  <SelectItem value="216">South Sudan, Republic of</SelectItem>
  <SelectItem value="217">Spain</SelectItem>
  <SelectItem value="218">Sri Lanka</SelectItem>
  <SelectItem value="219">Sudan</SelectItem>
  <SelectItem value="220">Suriname</SelectItem>
  <SelectItem value="221">Svalbard and Jan Mayen</SelectItem>
  <SelectItem value="222">Swaziland</SelectItem>
  <SelectItem value="223">Sweden</SelectItem>
  <SelectItem value="11">Switzerland</SelectItem>
  <SelectItem value="224">Syrian Arab Republic</SelectItem>
  <SelectItem value="225">Taiwan</SelectItem>
  <SelectItem value="226">Tajikistan</SelectItem>
  <SelectItem value="227">Tanzania, United Republic of</SelectItem>
  <SelectItem value="228">Thailand</SelectItem>
  <SelectItem value="229">Timor-Leste</SelectItem>
  <SelectItem value="230">Togo</SelectItem>
  <SelectItem value="231">Tokelau</SelectItem>
  <SelectItem value="232">Tonga</SelectItem>
  <SelectItem value="233">Trinidad and Tobago</SelectItem>
  <SelectItem value="234">Tristan da Cunha</SelectItem>
  <SelectItem value="235">Tunisia</SelectItem>
  <SelectItem value="236">Turkey</SelectItem>
  <SelectItem value="237">Turkmenistan</SelectItem>
  <SelectItem value="238">Turks and Caicos Islands</SelectItem>
  <SelectItem value="239">Tuvalu</SelectItem>
  <SelectItem value="240">Uganda</SelectItem>
  <SelectItem value="241">Ukraine</SelectItem>
  <SelectItem value="242">United Arab Emirates</SelectItem>
  <SelectItem value="1">United Kingdom</SelectItem>
  <SelectItem value="3">United States</SelectItem>
  <SelectItem value="243">United States Minor Outlying Islands</SelectItem>
  <SelectItem value="244">Uruguay</SelectItem>
  <SelectItem value="245">Uzbekistan</SelectItem>
  <SelectItem value="246">Vanuatu</SelectItem>
  <SelectItem value="247">Venezuela, Bolivarian Republic of</SelectItem>
  <SelectItem value="248">Viet Nam</SelectItem>
  <SelectItem value="249">Virgin Islands, British</SelectItem>
  <SelectItem value="250">Virgin Islands, U.S.</SelectItem>
  <SelectItem value="251">Wallis and Futuna</SelectItem>
  <SelectItem value="252">Western Sahara</SelectItem>
  <SelectItem value="253">Yemen</SelectItem>
  <SelectItem value="254">Zambia</SelectItem>
  <SelectItem value="255">Zimbabwe</SelectItem>
  </>
)
